name: syntax-tree
version: 0.1.0.0
github: "lamdu/syntax-tree"
license: BSD3
author: "Yair Chuchem"
maintainer: "yairchu@gmail.com"
copyright: 2018 Yair Chuchem"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Typed ASTs
category: Algorithms, Compilers/Interpreters, Language, Logic, Unification

description: Please see the README on GitHub at <https://github.com/lamdu/syntax-tree#readme>

dependencies:
- base
- constraints
- containers
- lattices
- lens
- monad-st
- mtl
- transformers
- pretty

library:
  source-dirs: src
  dependencies:
  - array
  - base-compat
  - binary
  - deepseq
  - pretty
  - QuickCheck
  - show-combinators
  - template-haskell
  - th-abstraction
  ghc-options:
  - -O2
  - -Wall
  - -Wnoncanonical-monad-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  ghc-prof-options:
  - -O2

tests:
  syntax-tree-test:
    main: Spec.hs
    source-dirs: test
    other-modules:
    - LangA
    - LangA.Pure
    - LangB
    - LangB.Pure
    - TypeLang
    - TypeLang.Pure
    ghc-options:
    - -Wall
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syntax-tree

benchmarks:
  syntax-tree-bench:
    main: Benchmark.hs
    source-dirs: test
    other-modules:
    - LangB
    - TypeLang
    - TypeLang.Pure
    ghc-options:
    - -O2
    - -Wall
    - -Wnoncanonical-monad-instances
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - criterion
    - syntax-tree
