name:                syntax-tree
version:             0.1.0.0
github:              "githubuser/syntax-tree"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/syntax-tree#readme>

dependencies:
- base
- constraints
- containers
- lens
- monad-st
- mtl
- transformers

library:
  source-dirs: src
  dependencies:
  - base-compat
  - binary
  - deepseq
  - pretty
  - QuickCheck
  - show-combinators
  - template-haskell
  - th-abstraction
  ghc-options:
  - -O2
  - -Wall
  - -Wnoncanonical-monad-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

tests:
  syntax-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syntax-tree
