name: hypertypes
version: 0.1.0.1
github: "lamdu/hypertypes"
license: BSD3
author: "Yair Chuchem"
maintainer: "yairchu@gmail.com"
copyright: 2018 Yair Chuchem"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Typed ASTs
category: Algorithms, Compilers/Interpreters, Language, Logic, Unification

description: Please see the README on GitHub at <https://github.com/lamdu/hypertypes#readme>

dependencies:
- base >= 4.9 && <5
- constraints
- containers
- generic-constraints
- generic-data
- lattices
- lens
- monad-st
- mtl
- transformers
- pretty

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DerivingStrategies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

library:
  source-dirs: src
  other-modules:
  - AST.TH.Internal.Instances
  - AST.TH.Internal.Utils
  dependencies:
  - array
  - base-compat
  - binary
  - deepseq
  - pretty
  - QuickCheck
  - show-combinators
  - template-haskell
  - th-abstraction >= 0.3
  default-extensions:
  - NoImplicitPrelude
  ghc-options:
  - -fexpose-all-unfoldings
  - -Wall
  - -Wnoncanonical-monad-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  ghc-prof-options:
  - -fexpose-all-unfoldings

tests:
  hypertypes-test:
    main: Spec.hs
    source-dirs: test
    other-modules:
    - LangA
    - LangA.Pure
    - LangB
    - ReadMeExamples
    - TypeLang
    - TypeLang.Pure
    ghc-options:
    - -Wall
    - -Wcompat
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hypertypes
    - text

benchmarks:
  hypertypes-bench:
    main: Benchmark.hs
    source-dirs: test
    other-modules:
    - LangB
    - TypeLang
    - TypeLang.Pure
    ghc-options:
    - -O2
    - -Wall
    - -Wnoncanonical-monad-instances
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - criterion
    - hypertypes
